name: Label PR with Target Branch

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  add-label:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract target branch name
      id: extract-branch
      run: |
        echo "::set-output name=target_branch::${GITHUB_REF#refs/heads/}"

    - name: Add label to PR
      run: |
        const github = require('@actions/github');
        const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
        const { owner, repo } = github.context.repo;
        const pr_number = github.context.payload.pull_request.number;
        const targetBranch = process.env.TARGET_BRANCH;

        octokit.issues.addLabels({
          owner,
          repo,
          issue_number: pr_number,
          labels: [targetBranch]
        });
